---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

  - name: install boto
    command: sudo apt-get -y install python-boto

  - name: Get credentials from vault
    include_vars:
      file: password.yml
      name: vault
  - name: set variables
    set_fact:
      hostname: service
      py_path: /usr/bin/python 
   
  - name: Create a new EC2 host
    ec2:
      aws_access_key: "{{ vault['aws_access_key'] }}"
      aws_secret_key: "{{ vault['aws_secret_key'] }}"
      key_name: skey
      instance_type: t2.micro
      image: ami-3213a748
      wait: yes
      region: us-east-1
      vpc_subnet_id: subnet-c36b5fef
      count: 1
      assign_public_ip: yes
    register: ec2

  - debug:
      var: ec2.instances[0].public_ip

  

  - name: add ec2 host
    add_host:
      name: "{{ ec2.instances[0].public_ip }}"
      groups: "{{ hostname }}"
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: /home/ubuntu/keys/skey.pem
      ansible_python_interpreter: "{{ py_path }}"
      host_key_checking: false

  - name: Wait for ec2 instance to bootup
    wait_for: 
      host: "{{ ec2.instances[0].public_ip }}" 
      port: 22 
      delay: 60 
      timeout: 320 
      state: started 
 
  - name: accept new ssh fingerprints                                         
    shell: ssh-keyscan -H {{ ec2.instances[0].public_ip }} >> ~/.ssh/known_hosts

- hosts: service
  gather_facts: no
  become_user: root

  tasks:
  - name: sample test
    shell: echo HELLO

   

